var storyData = `label,author,conditions,lock,weight,question,yes_answer,yes_response,Morale,Quality,Schedule,Budget,yes_outcome,no_answer,no_response,Morale,Quality,Schedule,Budget,no_outcome,Author
,PROGRAMMER,,10,50,We've got a ton of bugs we need to sort through! It's never ending.,Fix em!,I'm on it!,-5,15,-10,,,Who cares?,"I care! Whatever, you're the game director.",,-10,,5,,
,ARTIST,,10,50,I don't like the direction of our art style. We need to redo it.,Do it.,Thank you! This game is gonna look great!,,10,-10,,,We can't...,Bummer.,,-10,,5,,
,DESIGNER,,10,50,It's taking too much time to make all these levels. Can we cut back the scale of the game?,Sure,"Cutting content hurts, but it'll make the game better.",5,,5,,,Nope,But it's so much work!,,,,-10,,
,SOUND DESIGNER,,10,50,We need a new sound studio to record our SFX. How 'bout it?,Lets do it,Oooohh! My dreams have come true!,,,,-20,,Too expensive,"And once again, sound takes a backseat. You'll regret it!",,,,,20,
,PRODUCER,stats.budget >= 70,10,50,The project is under budget. Should we splurge and do something nice for the team?,Pizza Party!,Woot! Woot!,10,,,-10,,Let's be frugal.,Very good.,-5,,,,5,
,PRODUCER,stats.time >= 70,10,50,The project is ahead of schedule. Should we let the team take some time off?,They've earned it.,"Vacation, here I come!",15,,-10,,,Get back to work!,Rude.,-10,,,5,,
,PROGRAMMER,programmer_ate_pudding == false;,10,50,I found this pudding in the fridge. I want to eat it. I should it eat it. Can I eat it?,Go for it,So delicious!,5,,,,programmer_ate_pudding = true;,Maybe don't,I guess you're right.,-5,,,,,
,ARTIST,programmer_ate_pudding == true;,10,50,Did you seriously let the engineer eat my pudding from the fridge!? How could you!?,I'll buy you another,And it better be the same brand of pudding.,5,,,,,Get over it!,Oh! I will have my revenge. Just you wait.,-10,-5,,,,
,PRODUCER,stats.budget <= 30,10,50,We are extremely overbudget! We need to lay some staff off.,Do it,I hate this part of the job.,,,,,,Never!,I'm sure the team will appreciate it.,,,,,,
,ARTIST,,10,50,How much should we invest in the fidelity of our art.,We need the best graphics.,I agree.,5,10,-5,-5,,Graphics aren't important.,Bummer.,,-10,5,5,,
,PROGRAMMER,,10,50,I'm superior to all the other programmers on the team! Wouldn't you agree?,Of course you are,"And by your own admission, I deserve a raise.",-5,,,-5,,Absolutely not,Hmmmm. Well then maybe I should quit.,5,-5,,,,
,DESIGNER,,10,50,The moment-to-moment gameplay is boring. We need more juice in our game.,You're right!,I'll spend a week getting things in tip-top shape.,,5,,-10,,Not now,Ok. I hope players enjoy a boring game.,,-5,,,,
,PRODUCER,,10,50,The engineers are arguing again. Productivity is dropping.,Let them argue,They're all adults. They should be able to sort it out themselves.,-5,,5,,,Sort it out,Ugh. Why am I always having to babysit everyone.,5,,-5,-5,,
,QA LEAD,,10,50,"Playtsters are reporting some sort of rare glitch, but it is really rare. Worth looking into?",Focus on quality despite the cost.,"Smart choice. if there's a glitch, everyone will find out about it.",3,12,-25,30,qa_intense = true;,The cost is too high for a rare bug.,Smart choice: better to focus on the stuff most people see.,3,-25,20,-15,qa_gaveup = true;,
,QA LEAD,qa_intense == true;,10,50,"Been trying find that glitch, but we can't reproduce the bug! Should we move on?","Yes, mark as WONTFIX","The glitch is going to haunt me, gnawing away in the back of my mind, but ok.",-20,-10,1,,qa_gaveup = true;,"No, keep going, do not give up!","It'll take forever to find! Oh well, at least I'll be able to sleep at night.",,,,,,
,QA LEAD,qa_gaveup == true;,10,50,I've been having trouble sleeping. I keep thinking about that glitch...,Don't worry so much!,I guess you're right - we have other tasks to take care of anyways.,,,,,,Maybe we should try looking for it again.,Thank you! I need to get to the bottom if this!,,,,,,
,QA LEAD,,10,50,"I put in more hours than anyone around here, but I get no respect!",But you're ONLY a tester.,That hurts! This is very technical and hard work...,-5,-5,-1,,,You are just as important as a coder.,Thank you! Together we make a great team.,5,15,,,,
,QA LEAD,,10,50,I'm so burnt out! I've played the latest 74 times this week.,How about a pizza party this Friday?,That would be so fun! We could all use a break!,10,-1,1,-1,,We need you to come in this weekend.,"My brain is going to explode, but I'll try my best to focus.",-24,11,-10,4,,
,PROGRAMMER,,10,50,I found some code in an open source engine! It looks pretty clean to use.,Use it!,Great!,5,-5,5,5,,Let's build it in house.,That's what I thought.,-5,5,,,,Cassidy
,ARTIST,,10,50,"I'm running behind schedule on character sketches, I could use some help.","Okay, we'll hire someone.",Perfect! Thank you!,10,5,,-15,,It isn't in the budget,I guess the sketches will be late.,-5,,-10,5,,Cassidy
,MARKETING,marketing_offered_interview == false;,10,50,We have an opportunity to have an interview on our game! Should we do it?,Heck yes! Sign us up!,Consider it done!,10,,,,marketing_offered_interview = true,We're not ready yet,Maybe another time.,-5,,,,,Cassidy
,INTERVIEWER,marketing_offered_interview == true;,10,50,We've heard great things about your game! What can you tell us about it?,Tell everything!,That sounds amazing! Can't wait to play it!,10,,-5,15,,Keep some secrets!,"Ooooh, a mystery! Can't wait to play it!",10,,-5,15,,Cassidy
,SOUND DESIGNER,,10,50,I found this website that has stock sounds. Should we use it?,Go ahead!,That will save me soooo much time!,,-5,10,5,,I'd prefer to keep it in house.,Back to the sound booth I go!,,5,-5,-5,,Cassidy
,MARKETING,stats.budget >= 40;,10,50,People are pirating our game! What should we do?,Open source the code!,Power to the players!,,,,-30,,Shut them down!,"Okay, the fans won't be happy!",10,,,20,,Cassidy
,LEVEL DESIGNER,,10,50,"I had this really cool idea for a level - we have trees, and cities, and this complicated puzzle that goes - …","Uh-huh, sure, go ahead!",Great! I'll go write it up!,10,5,-10,-10,,Stick to the Level Design document,"Oh, okay…",-10,,5,10,,Cassidy
,HUMAN RESOURCES,stats.morale <= 30 && stats.budget >= 30;,10,50,Employee morale is low. Should we cater in a lunch?,Go for it!,Perfect! I've got them on speed dial!,15,5,-5,-10,,Do we have the money for that?,Understandable.,-5,,5,15,,Cassidy
,HUMAN RESOURCES,stats.morale <= 10 && stats.budget >= 50;,10,50,Employee morale is low. Should we schedule an employee retreat?,I was thinking the same thing!,Consider it booked!,30,10,-10,-20,,Didn't we just take one?,No… but don't work too hard,-5,,10,25,,Cassidy
,HUMAN RESOURCES,,10,50,Employees are upset about the lunch food. Should we get a vending machine?,Yes we should!,I'm on it!,15,5,5,-10,,Tell them to pack a lunch.,Can do!,-10,,,10,,Cassidy
,CEO,stats.time >= 70;,10,50,"We are ahead of schedule, could we do a Game Jam week?",Let the creativity flow!,I've already built my team!,15,,-10,,,Get back to work.,Didn't hurt to ask.,-5,,,,,Cassidy
,HUMAN RESOURCES,,10,50,We should get a speaker to talk about burn out.,I agree!,I'll give them a call!,15,,-5,-10,,"If you love the work, it isn't burn out.","Okay, just take a break occasionally.",-10,-5,5,10,,Cassidy
,CEO,,10,50,Our beta release is going strong! We should consider increasing the game price!,Do it!,More budget money!,,,,20,,Keep the lower price.,"Understandable, keep the fans happy.",10,,,,,Cassidy
,SOUND DESIGNER,,10,50,We should hire professional voice actors for this part of the game.,You're right!,I know who to call!,,10,,-10,,Let's keep it in house.,Then I'm off to the booth!,,,,5,,Cassidy
,PRODUCER,,10,50,Our scope is too big. We can't do it all with in budget.,Increase the budget!,Perfect! Thanks!,5,,-10,-20,scope_has_shrunk = false,Let's zero in that scope!,"Phew, that is a relief.",-5,,15,20,scope_has_shrunk = true,Cassidy
,PROGRAMMER,scope_has_shrunk == true;,10,50,Why did we do all of that work if you were going to shrink the scope?,Maybe we can squeeze it in…,Great! I had to waste it.,5,,-5,-5,,Learn from them and grow!,You should ask us about scope changes,-10,,5,5,,Cassidy
,ARTIST,scope_has_shrunk == true;,10,50,What do we do with these animations if we aren't going to use them?,Perhaps we could squeeze it in…,"Oh good, this was my favorite.",5,,-5,-5,,Archive them.,*scoff* Fine,-10,,5,5,,Cassidy
,CEO,scope_has_shrunk == false;,10,50,Why did we go over budget and over scope? Where is the money coming from?,Crunch time?,Good. See to that.,-15,,5,5,,No more team lunches?,Good. See to that.,-15,,5,5,,Cassidy
,PRODUCER,,10,50,"We are not going to hit our release date, what should we do?",Extend the deadline!,Sure! But Marketing won't be happy.,10,,10,-10,,Crunch time!,Sure! But the employees wont be happy.,-10,,10,10,,Cassidy
,PRODUCER,,10,50,"We are not going to hit our release date, what should we do?",Release it anyway!,Sure! But the players won't be happy.,10,-10,,-10,,What can we cut?,I'll ask around.,-10,10,5,5,,Cassidy
,ARTIST,,10,50,"I've tried messaging the PROGRAMMER 10 times and he hasn't responded, what should I do?",Leave it to me.,Great! Thanks!,5,,,,programmer_meeting_called = true,Have you tried calling them?,No… I'll try that.,-5,,,,,Cassidy
,PROGRAMMER,programmer_meeting_called == true;,10,50,You asked for this meeting?,You're doing great!,Thank you! I'll keep it up!,5,,,,,Respond to your messages,"Oh, my out of office must still be on.",-5,5,,,,Cassidy
,LEVEL DESIGNER,,10,50,Do we want to emphasize graphics or story for our project?,Graphics,I'll message the Artist!,,10,5,,,Story,I'll message the Writer!,,10,5,,,Cassidy
,PRODUCER,,10,50,We should look into new equipment. We're using ancient tech from 2019.,Works for me!,Ill get it ordered!,10,10,,-20,,What we have is fine.,"Okay, but the Smithsonian may call.",-5,,,10,,Cassidy
,LEVEL DESIGNER,,10,50,I've been working 100 hour weeks. Can I go on vacation?,"Yes, of course!",Great! I'm going to zzz…,10,-5,-5,,,Back to your desk.,But I'm zzz…,-5,-5,-5,,,Cassidy
,CEO,,10,50,"I've been hearing about 'loot boxes', we should add them to our game.","Sure, we can do that.",Great! I hear money coming!,-10,-5,-5,20,,I don't think that fits --,Nonsense! We can make what we want!,-5,,,5,,Cassidy
,CEO,stats.time >= 50;,10,50,"I've been hearing about 'battle royale' games, we should make those.",Sure... I guess we can change everything for that.,Great! Top 10 here we come!,,,-20,30,,That changes the entire game.,Maybe next time.,5,,5,-5,,Cassidy
,ARTIST,,10,50,I've been offered a new position. My replacement will by my twin. Her name is also ARTIST.,Good luck! We'll miss you!,I enjoyed working here!,5,-5,,,,What about a 20% raise?,Then I'll stay here!,5,5,,-10,,Cassidy
,PROGRAMMER,,10,50,I'm not feeling this engine. We should build our own.,Go ahead!,Great! Now I need to learn how!,10,5,-10,-10,,"No, get back to work.",Fine. We'll use outdated engines.,-5,-5,10,10,,Cassidy
,ARTIST,,10,50,We should decorate the office with art from our game!,Love it!,I'll get started!,5,,,-5,,Minimalism is fine.,Minimalism is so 5 years ago.,-5,,,5,,Cassidy
,PRODUCER,,10,50,Employee morale is high. We should push them harder.,Sounds great!,Deadlines here we come!,-10,5,15,,,Let them be.,You don't want too lax of an office.,5,,-10,-5,,Cassidy
,PROGRAMMER,,10,50,Should we make an anti-piracy message for our game?,"Yes, make it dark.",I've got lots of ideas!,5,,,5,,"No, if they pirate it, they needed to.",Okay…,-5,,,-5,,Cassidy
,LEVEL DESIGNER,,10,50,Do we want an open world or strict levels?,Open world!,I'm on it!,5,,5,,,Strict Levels!,I'm on it!,5,5,,,,Cassidy
,PROGRAMMER,,10,50,So… I accidentally overwrote... all of the ARTIST's work…,Uh oh. I'll tell them.,Better you than me.,-5,,-5,,programmer_has_overwritten_truth = true,Maybe they won't notice?,Fingers crossed!,-5,,-5,,programmer_has_overwritten_truth = false,Cassidy
,ARTIST,programmer_has_overwritten_truth == true;,10,50,The PROGRAMMER overwrote my work? Can we get it back?,We'll try.,"Okay, just let me know.",5,,,-5,,Probably not.,I guess I'll have to start over.,-5,,-5,-5,,Cassidy
,ARTIST,programmer_has_overwritten_truth == false;,10,50,Did you know the PROGRAMMER overwrote my work!?,…Yes.,And no one told me!? ,-5,,-5,-5,,Did he!?,Now I have to do it all over!,-10,,-10,-5,,Cassidy
,CEO,,10,50,We're running into an issue with our IP. We may have to rebrand.,Consider it done.,I like your grit!,10,,-5,-5,,Maybe we make everything plural instead?,"Huh, I hadn't thought of that!",,,,,,Cassidy
,LEVEL DESIGNER,,10,50,Can we use existing lore or should we make our own?,Make our own!,Great! Here comes Super Toaster Dude!,5,,,-5,,Use existing lore!,Great! I have a great idea about Zeus!,,-5,5,,,Cassidy
,PRODUCER,,10,50,Should we invest in backup software in case the game crashes?,Yes. Do that yesterday!,I'm on it!,,,,-10,purchased_backup = true,"No, we should be fine.",Okay. It makes me nervous…,,,,,purchased_backup = false,Cassidy
,PRODUCER,purchased_backup == true;,10,50,"There was a whole system crash. Luckily, we have back up!",The backup came in handy!,Very much so!,,,-5,-5,,Good thing we had the backup!,Indeed!,,,-5,-5,,Cassidy
,PRODUCER,purchased_backup == false;,10,50,There was a whole system crash! We lost 40% of our game!,Oh no!,We got some of it back.,,,-30,-30,,Uh oh!,We recovered some of it.,,,-30,-30,,Cassidy
,MASTER CODER,,10,50,What is the true nature of code?,Infinite possibility space,I prefer staying under 640k. Limitations are what drive creativity.,,,,,,Produce output as per the specs,Rigidity and formality make for solid apps but boring games.,,,,,,
,MASTER CODER,,10,50,I reject the concept of null!,Because it is NaN?,A feeling has no numerical value!,,,,,,Think of it as falsy and stop worrying.,Next you'll tell me that undefined and zero are equivalent.,,,,,,
,MASTER CODER,,10,50,"To test or not to test, that is the question?",Test and move slowly,"Measure twice, cut once, I suppose!",,15,20,10,,Let QA sort it out and move fast,"Until you open the box, the cat is both there and not there.",,-5,-5,-25,,
,MASTER CODER,,10,50,"More comments, or longer variable names?",Comments,"Okay, every function is now well  documented.",5,0,-10,,,Self documenting code,Good code is its own best documentation.,2,-1,-10,-10,,
,MASTER CODER,,10,50,Does anyone ever read GDDs? They get so stale by the end.,Better plan it all out.,Weeks of coding can save you hours of planning.,,,,,,Dive in and be reactive.,We can improvise along the way and iterate.,,,,,,
,MASTER CODER,,10,50,How can we be confident in our code?,Unit tests,"Testing shows the presence, not the absence of bugs.",,,,,,Playtests,Users can find things we miss.,,,,,,
,MASTER CODER,,10,50,We had the intern merge bad code to the main branch. Should we spend time to fix it? ,"Yes, let's revert and fix it.",I'm on it.,,5,-5,,,It should be fine,Maybe it won't break anything.,,-5,5,,,Cassidy
,MARKETING,,10,50,We should create a large marketing campaign for the game.,Go for it! ,Good! I already booked it.,5,,,-20,marketing_has_budget = true;,Lets stick with the plan.,Okay… Maybe word of mouth is good enough.,-5,,,5,,Cassidy
,MARKETING,marketing_has_budget == true && stats.budget < 40;,10,50,The marketing campaign paid off! We have lots of pre orders! ,Woohoo!,I'm a genius.,10,,,40,marketing_has_budget =false,Good to hear! ,Now to think of my next idea.,10,,,40,,Cassidy
,MARKETING,marketing_has_budget == true && stats.budget > 70;,10,50,The marketing campaign…didn't quite work. People are cancelling their pre orders.,That's not good.,I'll try another idea later.,-10,,,-20,marketing_has_budget =false,Go back to your desk.,The next idea will be better! ,-10,,,-20,,Cassidy
,HUMAN RESOURCES,,10,50,"We should create a ""Bring your pet to work"" Day",Sounds great! ,Perfect! I'll bring my cat! ,5,,,,,"No, I'm allergic.",Not a problem!,-5,,,,,Cassidy
,HUMAN RESOURCES,stats.budget > 40 && stats.morale <30;,10,50,"Employee morale is low, we should build a game room in the office.",Great idea! ,Great! I'll brush up my Pong skills. ,10,,,-10,,"We make games, not play them.",Don't push employees too hard!,-5,,,5,,Cassidy
,MARKETING,,10,50,"Should we get a booth at E4, the world's largest gaming convention!",Of course!,I'll find us a table!,5,5,,-10,,Not this year.,Bummer.,,,,5,,Cassidy
,PRODUCER,,10,50,Some employees want to work from home. Should we let them?,Yes they can! ,Okay! I'm on it!,5,,-5,5,,"No, in the office is better.",Makes sense.,-5,5,5,,,Cassidy
,QA LEAD,,10,50,The playtesters are saying the game is too hard.,Soften it up.,On it.,,-5,5,,,Increase the difficulty more.,On it.,,5,5,,,Cassidy
,CEO,,10,50,Our lawyers say our game is too similar to our competitor. What should we do?,Change it.,Good plan.,-10,10,-10,,,Don't change it.,You know best. ,10,-10,10,,,Cassidy
,SOUND DESIGNER,,10,50,I’m not liking our fighting sound effects.,Back to the booth!,On it!,,5,-5,,,We can't afford the changes.,Understood.,,-5,5,,,Cassidy
,LEVEL DESIGNER,,10,50,We should install a mo-cap booth!,I love it! ,Yay! ,10,10,,-20,,I hate it!,"Ouch, little harsh. ",-10,,5,5,,Cassidy
,PRODUCER,,10,50,Our sprint is running out of time. Can we have an extension? ,Yes.,"Phew, good.",5,5,-5,-5,,No.,Crunch time it is.,-5,-5,5,5,,Cassidy
,CEO,,10,50,I should speak to the team to tell them how we're doing and boost morale.,Good idea! ,Excellent.,5,,-5,,,"Eh, that'll put us behind. ",You'll figure it out.,5,,-5,,,Cassidy
,ARTIST,,10,50,Do you like the realistic art or more cartoony?,Realistic,I thought so too.,,5,5,,,Cartoony,Good! Me too! ,5,,5,,,Cassidy
,INTERN,,10,50,I think I broke the game.,That's how we learn.,You're right.,5,-5,,,,Don't touch anything else.,Okay.,-5,,-5,,,Cassidy
,INTERN,,10,50,It is my first day! Who should I go help?,Help the artist.,Can do!,,,,,intern_help_art = true,Help the programmer.,Can do!,,,,,intern_help_programmer = true,Cassidy
,ARTIST,intern_help_art == true && training_program_starting ==false;,10,50,Perhaps the Intern would be better on another team. They aren't helping here.,We all have to learn somehow.,I guess so.,5,-5,,,,Let's create a training program.,Good idea.,5,,,-5, training_program_starting =true,Cassidy
,PROGRAMMER,intern_help_programmer == true && training_program_starting ==false;,10,50,…The Intern is not helping me.,We all have to learn somehow.,But not in my department. ,5,,-5,,,Let's create a training program.,Works for me. ,5,,,-5, training_program_starting =true,Cassidy
,PRODUCER, training_program_starting ==true;,10,50,The training program is going well! We should put more effort into it! ,Go ahead!,Great!,10,10,-5,-10,,Let's wait and see.,Okay.,,,5,5, training_program_starting =false,Cassidy
,MARKETING,,10,50,We should spend some money on a professional trailer.,Good idea! ,I'm on it!,,,,-5,advanced_trailer_bought = true,Let's do it in house.,You can't spend yourself out of bad quality.,,,,,advanced_trailer_not_bought = true,Cassidy
,MARKETING,advanced_trailer_bought == true;,10,50,The trailer came out beautifully! Pre-orders are rolling in!,Glad it worked out!,Just doing my job!,5,,,15,advanced_trailer_bought = false,Way to go! ,No 'I' in Team!,5,,,15,advanced_trailer_bought = false,Cassidy
,MARKETING,advanced_trailer_not_bought == true;,10,50,The trailer didn't come out as expected. People aren't buying the game.,Live and learn.,I guess so.,-5,,,5,advanced_trailer_not_bought == false,We'll get 'em next time.,If you say so.,-5,,,5,advanced_trailer__not_bought == false,Cassidy
,PRODUCER,,10,50,"We extracted a system from a previous game, should we put it into the game?",Let's do it! ,Perfect!,,-5,5,,,Let's iterate and make it better.,Done and done!,,5,-5,,,Cassidy
,PRODUCER,,10,50,We should outsource this system. It'll save some time.,Go ahead!,I know who to call!,,,10,-10,,Let's do it ourselves.,That's what I thought.,,5,-5,,,Cassidy
,CEO,stats.budget < 20;,10,50,We should do some contract work to bolster revenue.,"Begrudingly, yes.",Good plan.,,,-10,10,,We don't have time.,We better make money soon then.,,,,,,Cassidy
,HUMAN RESOURCES,,10,50,We should increase our 401k matching contributions.,I like that idea!,I'm on it!,5,,,-5,,A 401 what now?,Nevermind then.,-5,,,5,,Cassidy
,PRODUCER,,10,50,Should we purchase development kits for the new consoles that are coming out?,Yes we should!,I'll pick one up! ,5,5,,-5,,Not quite yet. ,"If not now, then when?",-5,,5,5,,Cassidy
,SOUND DESIGNER,,10,50,These VO lines didn't come out right. Should we do them again? ,We should.,I'll call the actors back.,,5,-5,,,They're good enough.,If you say so.,,-5,5,,,Cassidy
,ARTIST,,10,50,I believe we are underpaid compared to our competitors. ,We should fix that. Raise for everyone!,Yay!,10,,,-10,,It is what we can afford.,I may leave soon if things don't change.,-5,,,5,,Cassidy
,CEO,,10,50,We should have a game jam week for new ideas.,Great idea! ,I always have them.,10,,-10,,,Not right now.,Don't burn the employees out.,-5,,5,,,Cassidy
,MARKETING,,10,50,We should create an online video channel to build some hype.,Go for it! ,Can do! ,,,,-5,video_channel_created = true,Let's keep it all hush hush.,Say no more. ,,,,,,Cassidy
,MARKETING,video_channel_created == true,10,50,The video channel is really taking off! People love the content!,Good move! ,I try my best!,5,,5,10,,Good idea! ,I'm a master planner!,5,,5,10,,Cassidy
,HUMAN RESOURCES,,10,50,We should have a costume day! ,I'll get my T-Rex outfit! ,I'll find my cat ears!,5,,,,,Not now. ,Not a problem!,,,5,,,Cassidy
,CEO,,10,50,There has been a change in tax law. We owe more than expected.,Out of our control. ,I know.,,,,-5,,Fine.,My thoughts exactly.,,,,-5,,Cassidy
,HUMAN RESOURCES,stats.morale < 30,10,50,"People are complaining about work conditions, what should we do? ",Suggestion box!,Good idea!,5,,,,suggestion_box_active = true,"If they don't like it, they can leave. ",If you think that's best.,-10,-5,-5,-5,,Cassidy
,LEVEL DESIGNER,suggestion_box_active == true,10,50,Could we add a free snack bar in the employee lounge room? ,Great idea! ,Yes! ,5,5,,-5,,Pass.,Okay…,-5,,,5,,Cassidy
,ARTIST,suggestion_box_active == true,10,50,Could we start working half days on Fridays? ,Good idea! ,Yay!,5,,-5,,,Not going to happen. ,Aww…,-5,,5,,,Cassidy
,INTERN,suggestion_box_active == true,10,50,Could the INTERNS get paid more?,Good idea! ,Yay! ,5,,,-5,,Not a good idea. ,Back to work I go.,-5,,,5,,Cassidy
,PROGRAMMER,suggestion_box_active == true,10,50,Could remote work be possible? ,Love it! ,Finally! Pajamas here I come!,5,,-5,,,Hate it!,Harsh. ,-5,,5,,,Cassidy
,MARKETING,suggestion_box_active == true,10,50,We should charge for tours of the company office! ,Good idea! ,I'll open the doors!,-5,,,5,,Won't that breach our NDA's? ,Good point.,5,,,-5,,Cassidy
,LEVEL DESIGNER,,10,50,We should add a custom level editor for the players to our game! ,Great idea! ,Perfect! ,,5,-5,,,Pass.,I'll get back to work then.,,-5,5,,,Cassidy
,SOUND DESIGNER,,10,50,Should we create our own OST or buy the rights to songs? ,Create our own OST,Off to the booth I go!,,5,,-5,create_ost = true,Buy track rights,Can do!,,,5,-5,,Cassidy
,MARKETING,create_ost == true,10,50,We should sell our OST!,Do it! ,Way ahead of you!,5,,,10,,Keep it in the game.,That’s a missed opportunity!,-5,,,-5,,Cassidy
,CEO,,10,50,"The cost of physically producing games is too high, we should go digital only.",I like physical copies!,You know best.,5,,,-10,,That's probably a good move.,It’s the way of the future.,-5,,,10,,Cassidy
,LEVEL DESIGNER,,10,50,I have a rather obscure idea for a level. I don't think a lot of people will like it.,Let's see it!,I'm on it!,5,5,,-5,,Let's do what the audience wants.,That's the safer plan.,-5,,5,5,,Cassidy
,ARTIST,,10,50,"I just have the art done, I don't think I can do the animation without working overtime. Should I do that? ",Overtime it is.,I'll clear my calendar.,-5,,5,,,It can wait.,If you think that's best.,,5,-5,,,Cassidy
,PROGRAMMER,,10,50,So… I may have deleted the Game Manager tool... The game isn't working. ,We have to fix it! ,I'm on it! ,,,-10,,,Did Ctrl+Z not work? ,Nope. I tried it. ,,,-10,,,Cassidy
,CEO,,10,50,We blew past our goals! Everyone gets a bonus and a raise! ,Yay!,Thought you might like that news!,10,,5,10,,Excellent!,Let's keep it up! ,10,,5,10,,Cassidy`;


/*
var storyData_WORKING_COPY = `label,author,conditions,lock,weight,question,yes_answer,yes_response,Morale,Quality,Schedule,Budget,yes_outcome,no_answer,no_response,Morale,Quality,Schedule,Budget,no_outcome
,PROGRAMMER,,10,50,We've got a ton of bugs we need to sort through! It's never ending.,Fix em!,I'm on it!,-5,15,-10,,,Who cares?,"I care! Whatever, you're the game director.",,-10,,5,
,ARTIST,,10,50,I don't like the direction of our art style. We need to redo it.,Do it.,Thank you! This game is gonna look great!,,10,-10,,,We can't...,Bummer.,,-10,,5,
,DESIGNER,,10,50,It's taking too much time to make all these levels. Can we cut back the scale of the game?,Sure,"Cutting content hurts, but it'll make the game better.",5,,5,,,Nope,But it's so much work!,,,,-10,
,SOUND DESIGNER,,10,50,We need a new sound studio to record our SFX. How 'bout it?,Lets do it,Oooohh! My dreams have come true!,,,,-20,,Too expensive,"And once again, sound takes a backseat. You'll regret it!",,,,,20
,PRODUCER,stats.budget >= 70,10,50,The project is under budget. Should we splurge and do something nice for the team?,Pizza Party!,Woot! Woot!,10,,,-10,,Let's be frugal.,Very good.,-5,,,,5
,PRODUCER,stats.time >= 70,10,50,The project is ahead of schedule. Should we let the team take some time off?,They've earned it.,"Vacation, here I come!",15,,-10,,,Get back to work!,Rude.,-10,,,5,
,PROGRAMMER,programmer_ate_pudding == false;,10,50,I found this pudding in the fridge. I want to eat it. I should it eat it. Can I eat it?,Go for it,So delicious!,5,,,,programmer_ate_pudding = true;,Maybe don't,I guess you're right.,-5,,,,
,ARTIST,programmer_ate_pudding == true;,10,50,Did you seriously let the engineer eat my pudding from the fridge!? How could you!?,I'll buy you another,And it better be the same brand of pudding.,5,,,,,Get over it!,Oh! I will have my revenge. Just you wait.,-10,-5,,,
,PRODUCER,stats.budget <= 30,10,50,We are extremely overbudget! We need to lay some staff off.,Do it,I hate this part of the job.,,,,,,Never!,I'm sure the team will appreciate it.,,,,,
,ARTIST,,10,50,How much should we invest in the fidelity of our art.,We need the best graphics.,I agree.,5,10,-5,-5,,Graphics aren't important.,Bummer.,,-10,5,5,
,PROGRAMMER,,10,50,I'm superior to all the other programmers on the team! Wouldn't you agree?,Of course you are,"And by your own admission, I deserve a raise.",-5,,,-5,,Absolutely not,Hmmmm. Well then maybe I should quit.,5,-5,,,
,DESIGNER,,10,50,The moment-to-moment gameplay is boring. We need more juice in our game.,You're right!,I'll spend a week getting things in tip-top shape.,,5,,-10,,Not now,Ok. I hope players enjoy a boring game.,,-5,,,
,PRODUCER,,10,50,The engineers are arguing again. Productivity is dropping.,Let them argue,They're all adults. They should be able to sort it out themselves.,-5,,5,,,Sort it out,Ugh. Why am I always having to babysit everyone.,5,,-5,-5,`;
*/